baseurl = "http://localhost/kuksa/"
#baseurl = "http://localhost/"
#baseurl = ""
title = "Eclipse KUKSA"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = "UA-XXXXX-X"
googleAnalytics = ""

# Define the number of posts per page
paginate = 10
# Adding this COMMENT for testing
# Adding this COMMENT2 for testing

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 10

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 15

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 20

[[menu.main]]
    name = "Talks & Videos"
    url  = "/publications/"
    weight = 30

[[menu.main]]
    name = "Resources"
    url  = "/resources/"
    weight = 40


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/eclipse?utf8=✓&q=kuksa"
    pre = "<i class='fa fa-2x fa-github'></i>"


[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:kuksa-dev@eclipse.org"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Admin"
    defaultKeywords = ["iot", "smart mobility", "kuksa", "appstacle", "SDV", "SOAFEE"]
    defaultDescription = "Eclipse KUKSA community website"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "turquoise"

    #about_us = "Doing the plumbing for the Software Defined Vehicle"

    copyright = "Copyright © 2018-2022 The Eclipse Foundation. All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

	logo = "img/kuksa-logo-h-209x79.png"
    logo_small = "img/kuksa-logo-h-209x79.png"
	#logo = "img/kuksa-logo-h.png"
   #address = """<p><strong>Universal Ltd.</strong>
   #     <br>13/25 New Avenue
   #     <br>Newtown upon River
   #     <br>45Y 73J
   #     <br>England
   #     <br>
   #     <strong>Great Britain</strong>
   #   </p>
   #   """
   # latitude = "-12.043333"
   # longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carrousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.

[params.footer.recent_posts]
    enable = false



[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Friends and Partners"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Our latest news"
    subtitle = ""

[params.about]
    enable = true
    title = "About Eclipse KUKSA"


